name: "游깷 Build the matrix.org website"
on: [workflow_dispatch, push, pull_request]
jobs:
  build-spec:
    name: "游닀 Spec"
    runs-on: ubuntu-latest
    container: "python:3.6"
    steps:
      - name: "游닌 Source checkout"
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: "游닌 matrix-doc OpenAPI artifact download"
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: main.yml
          workflow_conclusion: success
          repo: ${{ github.repository_owner }}/matrix-doc
          branch: ${{ github.ref }}
          name: openapi-artifact
      - name: "游닀 Update docs"
        run: |
          python3 -m venv env
          env/bin/pip install requests
          . env/bin/activate; scripts/update_docs.sh
      - name: "游닍 Tarball creation"
        run: tar -czf styled-docs.tar.gz content/docs
      - name: "游닋 Artifact upload"
        uses: actions/upload-artifact@v2
        with:
          name: styled-docs-artifact
          path: styled-docs.tar.gz
  build-jekyll:
    name: "游깷 Jekyll"
    runs-on: ubuntu-latest
    container:
      image: "matrixdotorg/matrixdotorg-build:0.2"
    steps:
      - name: "游닌 Source checkout"
        uses: actions/checkout@v2
      - name: "游뚾 Jekyll build"
        run: |
          . /env/bin/activate
          ./jekyll/generate.sh
          cp -rf ./pre-generated/* jekyll/_site/
      - name: "游닍 Tarball creation"
        run: tar -czf jekyll-site.tar.gz jekyll/_site
      - name: "游닋 Artifact upload"
        uses: actions/upload-artifact@v2
        with:
          name: spec-artifact
          path: jekyll-site.tar.gz
  build-gatsby:
    name: "游깷 Gatsby"
    runs-on: ubuntu-latest
    container:
      image: "matrixdotorg/matrixdotorg-gatsby:latest"
    steps:
      - name: "游닌 Source checkout"
        uses: actions/checkout@v2
      - name: "游뚾 Gatsby build"
        run: ln -s /opt/gatsby/node_modules . && gatsby build
        working-directory: gatsby
      - name: "游닍 Tarball creation"
        run: tar -czf gatsby-site.tar.gz public
        working-directory: gatsby
      - name: "游닋 Artifact upload"
        uses: actions/upload-artifact@v2
        with:
          name: gatsby-artifact
          path: gatsby/gatsby-site.tar.gz
  build-guides:
    name: "游닀 Implementation guides"
    runs-on: ubuntu-latest
    container:
      image: "buildpack-deps"
    steps:
      - name: "游닌 Source checkout"
        uses: actions/checkout@v2
      - name: "游뚾 Build implementation guides"
        run: |
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.1/mdbook-v0.4.1-x86_64-unknown-linux-gnu.tar.gz
          tar -xf mdbook-v0.4.1-x86_64-unknown-linux-gnu.tar.gz
          ./mdbook build server -d ${GITHUB_WORKSPACE}/implementation-guides/implementation-guides/server
          ./mdbook build client -d ${GITHUB_WORKSPACE}/implementation-guides/implementation-guides/client
          ./mdbook build application-services -d ${GITHUB_WORKSPACE}/implementation-guides/implementation-guides/application-services
          cp index.html ./implementation-guides/
        working-directory: implementation-guides
      - name: "游닍 Tarball creation"
        run: tar -czf implementation-guides.tar.gz implementation-guides
        working-directory: implementation-guides
      - name: "游닋 Artifact upload"
        uses: actions/upload-artifact@v2
        with:
          name: guides-artifact
          path: implementation-guides/implementation-guides.tar.gz

